app/views/ordenCompra.py
from datetime import timedelta
from app.forms import OrdenCompraForm
from flask import Blueprint, render_template,flash, request, redirect, url_for,flash, jsonify # type: ignore
from app import db
from app.models import *

bp = Blueprint('ordenCompra', __name__, url_prefix='/ordenCompra')

@bp.route('/', methods=['GET', 'POST'])
def get_ordenes_compra():
    estado_orden_compra=EstadoOrdenCompra.query.filter_by(nombre='En curso').first()
    form = OrdenCompraForm()
    form.articulo_id.choices = [(a.id, a.nombre_articulo) for a in Articulo.query.all()]
    form.estado_id.choices = [(estado_orden_compra.id, estado_orden_compra.nombre)]
    proveedores_unicos = {d.proveedor for d in DetalleProveedor.query.all()}
    form.detalle_proveedor_id.choices = [(proveedor.id, proveedor.nombre) for proveedor in proveedores_unicos]
  

    if form.validate_on_submit():
        
        orden_compra= OrdenCompra.query.filter_by(articulo_id=form.articulo_id.data,estado_id=EstadoOrdenCompra.query.filter_by(nombre='En curso').first().id).first()
        detalle_proveedor = DetalleProveedor.query.filter_by(proveedor_id=form.detalle_proveedor_id.data, articulo_id=form.articulo_id.data).first()
        if not detalle_proveedor:
            flash('El proveedor no vende este artículo', 'danger')
        elif orden_compra :
            flash('El articulo ya tiene una orden de compra en curso', 'danger')
        else:
            nueva_orden = OrdenCompra(
                lote=form.lote.data,
                articulo_id=form.articulo_id.data,
                estado_id=form.estado_id.data,
                detalle_proveedor_id=detalle_proveedor.id
            )
            try:
                db.session.add(nueva_orden)
                db.session.commit()
                flash('Orden de compra creada con éxito', 'success')
                return redirect(url_for('ordenCompra.get_ordenes_compra'))
            except Exception as e:
                db.session.rollback()
                flash(f'Error al crear la orden de compra: {str(e)}', 'danger')

    if form.errors:
        flash(f'Errores en el formulario: {form.errors}', 'danger')
        print("Errores del formulario:", form.errors)

    ordenes_compra = OrdenCompra.query.all()
    articulos= Articulo.query.all()

    return render_template('ordenes_compra/lista_ordenes_compra.html', ordenes_compra=ordenes_compra, form=form,articulos=articulos)

@bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def edit_orden_compra(id):
    orden = OrdenCompra.query.get_or_404(id)
    form = OrdenCompraForm(obj=orden)
    form.articulo_id.choices = [(a.id, a.nombre_articulo) for a in Articulo.query.all()]
    form.detalle_proveedor_id.choices= [(orden.detalle_proveedor.id,orden.detalle_proveedor.proveedor.nombre)]
    form.estado_id.choices = [(e.id, e.nombre) for e in EstadoOrdenCompra.query.all()]

    if form.validate_on_submit():

        orden.lote = form.lote.data
        orden.articulo_id = form.articulo_id.data
        orden.estado_id = form.estado_id.data

        try:
            db.session.commit()
            flash('Orden de compra actualizada con éxito', 'success')
            return redirect(url_for('ordenCompra.get_ordenes_compra'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error al actualizar la orden de compra: {str(e)}', 'danger')

    return render_template('ordenes_compra/editar_orden_compra.html', form=form, orden=orden)

@bp.route('/eliminar/<int:id>')
def eliminar_orden_compra(id):
    orden = OrdenCompra.query.get_or_404(id)
    db.session.delete(orden)
    db.session.commit()
    flash('Orden de compra eliminada con éxito', 'success')
    return redirect(url_for('ordenCompra.get_ordenes_compra'))


@bp.route('/crear/<int:id>', methods=['GET', 'POST'])
def crear_orden_compra_articulo (id):
    articulo = Articulo.query.get_or_404(id)
    estado_orden_compra=EstadoOrdenCompra.query.filter_by(nombre='En curso').first()

    form = OrdenCompraForm()
    form.articulo_id.choices = [(articulo.id, articulo.nombre_articulo)]
    form.estado_id.choices = [(estado_orden_compra.id, estado_orden_compra.nombre)]
    form.detalle_proveedor_id.choices = [(dp.id, dp.proveedor.nombre) for dp in articulo.detalles_proveedor]

    lote=articulo.calcular_lote_a_comprar()

    if form.validate_on_submit():
        orden_compra= OrdenCompra.query.filter_by(articulo_id=form.articulo_id.data,estado_id=EstadoOrdenCompra.query.filter_by(nombre='En curso').first().id).first()
        if orden_compra :
            flash('El articulo ya tiene una orden de compra en curso', 'danger')
        else :
            nueva_orden = OrdenCompra(
                lote=form.lote.data,
                estado_id=form.estado_id.data,
                articulo_id=articulo.id,
                detalle_proveedor_id=form.detalle_proveedor_id.data
            )
            try:
                db.session.add(nueva_orden)
                db.session.commit()
                flash('Orden de compra creada con éxito', 'success')
                return redirect(url_for('ordenCompra.get_ordenes_compra'))
            except Exception as e:
                db.session.rollback()
                flash(f'Error al crear la orden de compra: {str(e)}', 'danger')
    
    return render_template('ordenes_compra/crear_orden_compra_articulo.html', form=form, articulo=articulo,lote=lote)


@bp.route('/actualizar_orden_finalizada', methods=['GET', 'POST'])
def actualizar_orden_finalizada():
    ordenes = OrdenCompra.query.filter_by(estado_id=EstadoOrdenCompra.query.filter_by(nombre='En curso').first().id).all()
    for orden in ordenes :
        demora = timedelta(days=orden.detalle_proveedor.tiempo_demora)
        if date.today()>=(orden.fecha + demora) :
            estado_orden_compra=EstadoOrdenCompra.query.filter_by(nombre='Finalizado').first()
            orden.estado_id =estado_orden_compra.id
            orden.articulo.stock= orden.articulo.stock + orden.lote
    try:
        db.session.commit()
        flash('Orden de compra actualizadas con exito', 'success')
        return redirect(url_for('ordenCompra.get_ordenes_compra'))
    except Exception as e:
        db.session.rollback()
        return f'Error al actualizar el stock: {str(e)}', 500

app/templates/ordenes_compra/crear_orden_compra_articulo.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Órden de Compra para el Artículo {{ articulo.nombre_articulo }}</h1>

    <!-- Formulario para crear nueva orden de compra -->
    <div class="card mb-4">
        <div class="card-header">Crear Nueva Orden de Compra</div>
        <div class="card-body">
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    <label>{{ form.lote.label }}</label>
                    {{ form.lote(class="form-control", value=lote) }}
                </div>
                <div class="mb-3">
                    <label>{{ form.articulo_id.label }}</label>
                    {{ form.articulo_id(class="form-control") }}
                </div>
                <div class="mb-3">
                    <label>{{ form.estado_id.label }}</label>
                    {{ form.estado_id(class="form-control") }}
                </div>
                <div class="mb-3">
                    <label>{{ form.detalle_proveedor_id.label }} predeterminado</label>
                    {{ form.detalle_proveedor_id(class="form-control") }}
                </div>
                <div class="d-flex justify-content-start">
                    {{ form.submit(class="btn btn-primary") }}
                    <a href="{{ url_for('ordenCompra.get_ordenes_compra') }}" class="btn btn-secondary m-1">Volver</a>
                </div>
                
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/ordenes_compra/editar_orden_compra.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}

<div class="container mt-5">
    <div class="card">
        <div class="card-header">Editar Orden de Compra {{orden.nro_orden_compra}}</div>
        <div class="card-body">
            <form id="editOrderForm" method="POST" action="{{ url_for('ordenCompra.edit_orden_compra', id=orden.nro_orden_compra) }}">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.lote.label }}</label>
                    {{ form.lote(class="form-control") }}
                </div>
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.articulo_id.label }}</label>
                    {{ form.articulo_id(class="form-control", disabled=True) }}
                </div>
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.estado_id.label }}</label>
                    {{ form.estado_id(class="form-control") }}
                </div>
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.detalle_proveedor_id.label }}</label>
                    {{ form.detalle_proveedor_id(class="form-control", disabled=True)  }}
                </div>
                <div class="d-flex justify-content-start">
                    <button type="submit" class="btn btn-primary">Actualizar</button>
                    <a href="{{ url_for('ordenCompra.get_ordenes_compra') }}" class="btn btn-secondary m-1">Volver</a>
                </div>
                
            </form>
        </div>
    </div>
    
</div>

<!-- Modal para avisar sobre el cambio de estado a finalizado -->
<div class="modal fade" id="cambiarEstadoOrden" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Cambiar estado orden </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h4>¿Estás seguro que quieres finalizar la orden? Esto incrementará el stock automáticamente</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="cancelFinalize">Cancelar</button>
          <button type="button" class="btn btn-danger" id="confirmFinalize">Aceptar</button>
        </div>
      </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const estadoSelect = document.querySelector('#estado_id');
        const modal = new bootstrap.Modal(document.getElementById('cambiarEstadoOrden'));
        const confirmButton = document.getElementById('confirmFinalize');
        const cancelButton = document.getElementById('cancelFinalize');
        const form = document.getElementById('editOrderForm');
        let previousValue = estadoSelect.value;
        let finalizeSelected = false;

        form.addEventListener('submit', function(event) {
            if (estadoSelect.options[estadoSelect.selectedIndex].text === 'Finalizado') {
                event.preventDefault();
                modal.show();
                finalizeSelected = true;
            } else {
                finalizeSelected = false;
            }
        });

        confirmButton.addEventListener('click', function() {
            finalizeSelected = false;
            form.submit();
        });

        cancelButton.addEventListener('click', function() {
            estadoSelect.value = previousValue;
            modal.hide();
        });
    });
</script>


{% endblock %}

app/templates/ordenes_compra/lista_ordenes_compra.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}

<div class="container mt-5">
  <h1 class="mb-4">Órdenes de Compra</h1>
  <div class="d-flex justify-content-between align-items-start">
    <div class="btn-group">
        <button type="button" class="btn btn-secondary mb-3">Generar orden compra para un artículo</button>
        <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split mb-3" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
        </button>
      
        <ul class="dropdown-menu dropdown-menu-start">
            {% for articulo in articulos %}
                <li><a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('form-{{ articulo.id }}').submit();">{{ articulo.nombre_articulo }}</a></li>
                <form id="form-{{ articulo.id }}" action="{{ url_for('ordenCompra.crear_orden_compra_articulo', id=articulo.id) }}" method="POST" style="display: none;">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                </form>
            {% endfor %}
        </ul>
    </div>
    <a href="{{ url_for('ordenCompra.actualizar_orden_finalizada') }}" class="btn btn-primary">Actualizar estado ordenes</a>
</div>
  

    <!-- Formulario para crear nueva orden de compra -->
    <div class="card mb-4">
        <div class="card-header">Crear Nueva Orden de Compra</div>
        <div class="card-body">
            <form method="POST" action="{{ url_for('ordenCompra.get_ordenes_compra') }}">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.lote.label }}</label>
                    {{ form.lote(class="form-control") }}
                </div>
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.articulo_id.label }}</label>
                    {{ form.articulo_id(class="form-control") }}
                </div>
                <div class="mb-3">
                    <label for="codigo_articulo">{{ form.estado_id.label }}</label>
                    {{ form.estado_id(class="form-control") }}
                </div>
                <div class="mb-3">
                  <label for="codigo_articulo">{{ form.detalle_proveedor_id.label }}</label>
                  {{ form.detalle_proveedor_id(class="form-control") }}
                </div>
                {{ form.submit(class="btn btn-primary") }}
            </form>
        </div>
    </div>
</div>

<!-- Lista de órdenes de compra -->
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col" class="text-center align-middle">ID</th>
            <th scope="col" class="text-center align-middle">Fecha</th>
            <th scope="col" class="text-center align-middle">Lote</th>
            <th scope="col" class="text-center align-middle">Artículo</th>
            <th scope="col" class="text-center align-middle">Estado</th>
            <th scope="col" class="text-center align-middle">Proveedor</th>
            <th scope="col" class="text-center align-middle">Demora</th>
            <th scope="col" class="text-center align-middle">Precio articulo</th>
            <th scope="col" class="text-center align-middle">Editar</th>
            <th scope="col" class="text-center align-middle">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for orden in ordenes_compra %}
        <tr>
          <td>{{ orden.nro_orden_compra }}</td>
          <td>{{ orden.fecha.strftime('%Y-%m-%d') }}</td>
          <td>{{ orden.lote }}</td>
          <td>{{ orden.articulo.nombre_articulo }}</td>
          <td>{{ orden.estado_orden_compra.nombre }}</td>
          <td>{{ orden.detalle_proveedor.proveedor.nombre }}</td>
          <td>{{ orden.detalle_proveedor.tiempo_demora }}</td>
          <td>{{ orden.detalle_proveedor.precio_articulo }}</td>
          <td class="text-center align-middle">
            <a 
                class="btn btn-primary btn-sm {% if orden.estado_orden_compra.nombre == 'Finalizado' %}disabled{% endif %}" 
                href="{% if orden.estado_orden_compra.nombre != 'Finalizado' %}{{url_for('ordenCompra.edit_orden_compra', id=orden.nro_orden_compra) }}{% else %}#{% endif %}">
                Editar
            </a>
          </td>
          <td class="text-center align-middle">
            <button class="btn btn-danger btn-sm" id="btn-edit{{orden.nro_orden_compra}}" data-bs-toggle="modal" data-bs-target="#modalEliminar{{orden.nro_orden_compra}}">
                Eliminar
            </button>
          </td>
        </tr>

        <!-- modal borrar orden compra-->
      <div class="modal fade" id="modalEliminar{{orden.nro_orden_compra}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar orden de compra {{orden.nro_orden_compra}}</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h4>¿Estas seguro que quieres eliminar esta orden de compra?</h2>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <a href="{{url_for('ordenCompra.eliminar_orden_compra', id=orden.nro_orden_compra)}}"  class=" btn btn-danger">Aceptar</a>
            </div>
          </div>
        </div>
      </div>

        {% endfor %}
    </tbody>
</table>



{% endblock %}