app/views/proveedores.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, jsonify # type: ignore
from app import db
from app.forms import ProveedorFrom,DetalleProveedorForm,DetalleProveedorFormEditar
from app.models import *

bp = Blueprint('proveedores', __name__, url_prefix='/proveedores')

@bp.route('/', methods=['GET'])
def index():
    form_proveedor = ProveedorFrom()
    form_detalle_proveedor = DetalleProveedorForm()
    form_detalle_proveedor.proveedor_id.choices = [(p.id, p.nombre) for p in Proveedor.query.all()]
    form_detalle_proveedor.articulo_id.choices = [(a.id, a.nombre_articulo) for a in Articulo.query.all()]
    form_detalle_proveedor_editar = DetalleProveedorFormEditar()

    proveedores = Proveedor.query.all()
    articulos = Articulo.query.all()
    return render_template('proveedores/index.html', proveedores=proveedores, articulos=articulos,form_proveedor=form_proveedor,form_detalle_proveedor=form_detalle_proveedor,form_detalle_proveedor_editar=form_detalle_proveedor_editar)


@bp.route('/crear_proveedor', methods=['POST'])
def crear_proveedor():
    form = ProveedorFrom()

    if form.validate_on_submit():
        nuevo_proveedor=Proveedor(
            nombre=form.nombre.data
        )
        try:
            db.session.add(nuevo_proveedor)
            db.session.commit()
            flash('Proveedor creado exitosamente', 'success')
            return redirect(url_for('proveedores.index'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error al crear proveedor: {e}', 'danger')
           
    
    return redirect(url_for('proveedores.index', form=form))


@bp.route('/crear_detalle_proveedor', methods=['POST'])
def crear_detalle_proveedor():
    form=DetalleProveedorForm()
     # Populate SelectField choices
    form.proveedor_id.choices = [(p.id, p.nombre) for p in Proveedor.query.all()]
    form.articulo_id.choices = [(a.id, a.nombre_articulo) for a in Articulo.query.all()]

    if form.validate_on_submit(): 
        
        nuevo_detalle_proveedor=DetalleProveedor(
            proveedor_id=form.proveedor_id.data,
            costo_pedido_proveedor=form.costo_pedido_proveedor.data,
            tiempo_demora=form.tiempo_demora.data,
            precio_articulo=form.precio_articulo.data,
            articulo_id=form.articulo_id.data
        )
        try:
            db.session.add(nuevo_detalle_proveedor)
            db.session.commit()
            flash('Detalle proveedor creado exitosamente', 'success')
            return redirect(url_for('proveedores.index'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error al crear detalle provedor: {e}', 'danger')
    if form.errors:
        flash(f'Errores en el formulario: {form.errors}', 'danger')
        print("Errores del formulario:", form.errors) 
           
    
    return redirect(url_for('proveedores.index', form=form))


@bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar_detalle_proveedor(id):
    detalle_proveedor = DetalleProveedor.query.get_or_404(id)
    form = DetalleProveedorFormEditar(obj=detalle_proveedor)

    if form.validate_on_submit(): 
        detalle_proveedor.costo_pedido_proveedor = form.costo_pedido_proveedor.data
        detalle_proveedor.tiempo_demora = form.tiempo_demora.data
        detalle_proveedor.precio_articulo = form.precio_articulo.data

        try:
            db.session.commit()
            flash('Detalle proveedor editado exitosamente', 'success')
            return redirect(url_for('proveedores.index'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error al editar detalle proveedor: {e}', 'danger')

    if form.errors:
        flash(f'Errores en el formulario: {form.errors}', 'danger')
        print("Errores del formulario:", form.errors)        

    return redirect(url_for('proveedores.index', form=form, detalle_proveedor=detalle_proveedor))


@bp.route('/eliminar/<int:id>')
def eliminar_detalle_proveedor(id):
    articulo = Articulo.query.filter_by(detalle_proveedor_predeterminado_id=id).first()
    detalle_proveedor = DetalleProveedor.query.get_or_404(id)

    
    if articulo:  #Validacion que no haya ningun articulo apuntando es este detalle proveedor
        flash(f'No se puede eliminar el detalle proveedor porque está establecido como predeterminado para el articulo "{articulo.nombre_articulo}".', 'danger')
    else:
        db.session.delete(detalle_proveedor)
        db.session.commit()
        flash('Detalle proveedor eliminado con éxito', 'success')
    return redirect(url_for('proveedores.index'))
    

    

app/templates/proveedores/index.html
{% extends 'base.html' %}
{% block head %}

{% endblock %}

{% block body %}

<div class="container mt-4">
    <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#crearProveedorModal">Crear Proveedor</button>
        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#crearDetalleProveedorModal">Configurar nuevo detalle proveedor</button>
    </div>
</div>

<!-- Modal para crear proveedor -->
<div class="modal fade" id="crearProveedorModal" tabindex="-1" aria-labelledby="crearProveedorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="crearProveedorModalLabel">Crear Proveedor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ url_for('proveedores.crear_proveedor') }}">
                    {{ form_proveedor.hidden_tag() }}
                    <div class="mb-3">
                        <label>{{ form_proveedor.nombre.label }}</label>
                        {{ form_proveedor.nombre(class="form-control mb-3") }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        {{ form_proveedor.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal para crear detalle proveedor -->
<div class="modal fade" id="crearDetalleProveedorModal" tabindex="-1" aria-labelledby="crearDetalleProveedorLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="crearDetalleProveedorLabel">Configurar detalle proveedor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ url_for('proveedores.crear_detalle_proveedor') }}">
                    {{ form_detalle_proveedor.hidden_tag() }}
                    <div class="mb-3">
                        <label>{{ form_detalle_proveedor.proveedor_id.label }}</label>
                        {{ form_detalle_proveedor.proveedor_id(class="form-control mb-3") }}
                    </div>
                    <div class="mb-3">
                        <label>{{ form_detalle_proveedor.costo_pedido_proveedor.label }}</label>
                        {{ form_detalle_proveedor.costo_pedido_proveedor(class="form-control mb-3",type="number") }}
                    </div>
                    <div class="mb-3">
                        <label>{{ form_detalle_proveedor.precio_articulo.label }}</label>
                        {{ form_detalle_proveedor.precio_articulo(class="form-control mb-3",type="number") }}
                    </div>
                    <div class="mb-3">
                        <label>{{ form_detalle_proveedor.tiempo_demora.label }}</label>
                        {{ form_detalle_proveedor.tiempo_demora(class="form-control mb-3",type="number") }}
                    </div>
                    <div class="mb-3">
                        <label>{{ form_detalle_proveedor.articulo_id.label }}</label>
                        {{ form_detalle_proveedor.articulo_id(class="form-control mb-3") }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        {{ form_detalle_proveedor.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Tabla para mostrar proveedores/detalle proveedor-->
 {% for proveedor in proveedores %}
<h4 class="mt-4">{{proveedor.nombre}}</h4>
<div class="table-responsive">
    <table class="table table-striped table-sm table-bordered">
      <thead>
        <tr>
          <th scope="col" class="text-center align-middle">Codigo</th> 
          <th scope="col" class="text-center align-middle">Articulo</th> 
          <th scope="col" class="text-center align-middle">Costo pedido</th>
          <th scope="col" class="text-center align-middle">Precio articulo</th>
          <th scope="col" class="text-center align-middle">Tiempo de demora</th>
          <th scope="col" class="text-center align-middle">Editar</th>
          <th scope="col" class="text-center align-middle">Eliminar</th>
        </tr>
      </thead>
    {% for detalle_proveedor in proveedor.detalles_proveedor %}
        <tbody>
            <tr>
              <td class="text-center align-middle">{{detalle_proveedor.id}}</td>  
              <td class="text-center align-middle">{{detalle_proveedor.articulo.nombre_articulo}}</td>
              <td class="text-center align-middle">{{detalle_proveedor.costo_pedido_proveedor}}</td>
              <td class="text-center align-middle">{{detalle_proveedor.precio_articulo}}</td>
              <td class="text-center align-middle">{{detalle_proveedor.tiempo_demora}}</td>
              <td class="text-center align-middle"><button class="btn btn-primary btn-sm" id="btn-edit{{detalle_proveedor.id}}" data-bs-toggle="modal" data-bs-target="#modaleditar{{detalle_proveedor.id}}">Editar</button></td>
              <td class="text-center align-middle"><button class="btn btn-danger btn-sm" id="btn-edit{{detalle_proveedor.id}}" data-bs-toggle="modal" data-bs-target="#modalEliminar{{detalle_proveedor.id}}">Eliminar</button></td>
            </tr>

             <!-- modales editar detalle proveedor-->
            <div class="modal fade" id="modaleditar{{ detalle_proveedor.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Editar proveedor {{proveedor.nombre}} articulo {{ detalle_proveedor.articulo.nombre_articulo }}</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{{ url_for('proveedores.editar_detalle_proveedor', id=detalle_proveedor.id) }}" method="POST">
                                {{ form_detalle_proveedor_editar.hidden_tag() }}
                                <label>{{ form_detalle_proveedor_editar.costo_pedido_proveedor.label }}</label>
                                {{ form_detalle_proveedor_editar.costo_pedido_proveedor(class="form-control mb-3",type="number", value=detalle_proveedor.costo_pedido_proveedor) }}
                                <label>{{ form_detalle_proveedor_editar.precio_articulo.label }}</label>
                                {{ form_detalle_proveedor_editar.precio_articulo(class="form-control mb-3",type="number", value=detalle_proveedor.precio_articulo) }}
                                <label>{{ form_detalle_proveedor_editar.tiempo_demora.label }}</label>
                                {{ form_detalle_proveedor_editar.tiempo_demora(class="form-control mb-3",type="number",value=detalle_proveedor.tiempo_demora) }}
                                <div class="modal-footer">
                                    {{ form_detalle_proveedor_editar.submit(class="btn btn-primary") }}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

      <!-- modal borrar articulo-->
      <div class="modal fade" id="modalEliminar{{detalle_proveedor.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar  proveedor {{proveedor.nombre}} articulo {{ detalle_proveedor.articulo.nombre_artiuclo }}</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h4>¿Estas seguro que quieres eliminar este detalle proveedor?</h2>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <a href="{{url_for('proveedores.eliminar_detalle_proveedor', id=detalle_proveedor.id)}}"  class=" btn btn-danger">Aceptar</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
        </tbody>
    </table>
</div>
 {% endfor %}

{% endblock %}