app/views/demanda.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, flash
from app import db
from app.models import *
from app.forms import DemandaForm
from datetime import datetime

bp = Blueprint('demanda', __name__, url_prefix='/demanda')

@bp.route('/', methods=['GET'])
def get_demanda ():
    form = DemandaForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]
    
    demanda = Demanda.query.all()
    return render_template('demanda/demandaPage.html', demanda=demanda, form=form)  


@bp.route('/', methods=['POST'])
def crear_demanda():
    form = DemandaForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]

    if form.validate_on_submit():
        articulo_id = form.articulo_id.data
        fecha = form.fecha_d.data
        fecha_actual = datetime.now()

        if fecha.month < fecha_actual.month or fecha.year < fecha_actual.year:
            if Demanda.existe_demanda(articulo_id, fecha):
                flash('Ya existe una demanda para este artículo en el mismo mes y año.', 'error')
            else:
                cantidad_demanda = Venta.calcular_demanda_mes(articulo_id, fecha)
                nueva_demanda = Demanda(
                    cantidad=cantidad_demanda,
                    articulo_id=articulo_id,
                    fecha_d=fecha
                )
                try:
                    db.session.add(nueva_demanda)
                    db.session.commit()
                    flash('Demanda guardada con éxito!', 'success')
                except Exception as e:
                    db.session.rollback()
                    flash(f'Error al crear la demanda: {str(e)}', 'danger')
                return redirect(url_for('demanda.get_demanda'))
        else:
            flash('El mes no puede ser el actual', 'danger')
    if form.errors:
        flash(f'Errores en el formulario: {form.errors}', 'danger')
        print("Errores del formulario:", form.errors)
    return redirect(url_for('demanda.get_demanda'))



@bp.route('/eliminar/<int:id>')
def eliminar_demanda(id):
    demanda = Demanda.query.get_or_404(id)
    db.session.delete(demanda)
    db.session.commit()
    flash('Demanda eliminada con éxito', 'success')
    return redirect(url_for('demanda.get_demanda'))

@bp.route('/consultar', methods=['GET'])
def consultar_demanda():
    form = DemandaForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]

    fecha_inicio = request.args.get('fecha_inicio')
    fecha_fin = request.args.get('fecha_fin')
    articulo_id = request.args.get('articulo_id')

    demanda_consulta = []

    if fecha_inicio and fecha_fin and articulo_id:
        try:
            fecha_inicio = datetime.strptime(fecha_inicio, '%Y-%m')
            fecha_fin = datetime.strptime(fecha_fin, '%Y-%m')
            articulo_id = int(articulo_id)

            demanda_consulta = Demanda.query.filter(
                Demanda.fecha_d >= fecha_inicio,
                Demanda.fecha_d <= fecha_fin,
                Demanda.articulo_id == articulo_id
            ).all()
        except ValueError as e:
            flash(f'Error en los datos proporcionados: {str(e)}', 'danger')

    return render_template('demanda/demandaPage.html', form=form, demanda_consulta=demanda_consulta)

app/templates/demanda/demandaPage.html
{% extends 'base.html' %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

{% endblock %}

{% block body %}
<h2 class="mt-2">Gestión de Demanda</h2>
<div class="container">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" id="demandaTabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link {% if not demanda_consulta %}active{% endif %}" id="calcular-tab" data-bs-toggle="tab" href="#calcular" role="tab" aria-controls="calcular" aria-selected="false">Calcular Demanda</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="ver-tab" data-bs-toggle="tab" href="#ver" role="tab" aria-controls="ver" aria-selected="true">Ver Demanda</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if demanda_consulta %}active{% endif %}" id="consultar-tab" data-bs-toggle="tab" href="#consultar" role="tab" aria-controls="consultar" aria-selected="false">Consultar Demanda</a>  
    </li> 
  </ul>

  <!-- Tab panes -->
  <div class="tab-content" id="demandaTabContent">
    <!-- Pestaña Calcular Demanda -->
  <div class="tab-pane fade {% if not demanda_consulta %}show active{% endif %}" id="calcular" role="tabpanel" aria-labelledby="calcular-tab">
    <div class="card mt-3">
      <div class="card-body">
        <form method="POST" action="{{ url_for('demanda.crear_demanda') }}">
          {{ form.hidden_tag() }}
          <div class="row mb-3">
            <div class="col">
              <label>{{ form.articulo_id.label }}</label>
              {{ form.articulo_id(class="form-control mb-3") }}
            </div>
            <div class="col">
              <label>{{ form.fecha_d.label }}</label>
              {{ form.fecha_d(class="form-control mb-3") }}
            </div>
          </div>
          <div class="col d-flex justify-content-end">
            {{ form.submit(class="btn btn-primary") }}
          </div>
        </form>
      </div>
    </div>
  </div>
    <!-- Fin Pestaña Calcular Demanda -->

    <!-- Pestaña Ver Demanda -->
    <div class="tab-pane fade" id="ver" role="tabpanel" aria-labelledby="ver-tab">
      <div class="table-responsive mt-3">
        <table class="table table-striped table-sm table-bordered">
          <thead>
            <tr>
              <th scope="col" class="text-center align-middle">Codigo de Demanda</th>
              <th scope="col" class="text-center align-middle">Cantidad</th>
              <th scope="col" class="text-center align-middle">Código Artículo</th>
              <th scope="col" class="text-center align-middle">Nombre Artículo</th>
              <th scope="col" class="text-center align-middle">Fecha Calculo Demanda</th>
              <th scope="col" class="text-center align-middle">Eliminar</th>
            </tr>
          </thead>
          <tbody>
            {% for demanda in demanda %}
            <tr>
              <td class="text-center align-middle">{{ demanda.id }}</td>
              <td class="text-center align-middle">{{ demanda.cantidad }}</td>
              <td class="text-center align-middle">{{ demanda.articulo.codigo_articulo }}</td>
              <td class="text-center align-middle">{{ demanda.articulo.nombre_articulo }}</td>
              <td class="text-center align-middle">{{ demanda.fecha_d }}</td>
              <td class="text-center align-middle">
                <button class="btn btn-danger btn-sm" id="btn-edit{{ demanda.id }}" data-bs-toggle="modal" data-bs-target="#modalEliminar{{ demanda.id }}">Eliminar</button>
              </td>
            </tr>
            <!-- modal borrar demanda -->
            <div class="modal fade" id="modalEliminar{{ demanda.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar demanda numero: {{ demanda.id }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <h4>¿Estas seguro que quieres eliminar esta demanda?</h4>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <a href="{{ url_for('demanda.eliminar_demanda', id=demanda.id) }}" class="btn btn-danger">Aceptar</a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- Fin Pestaña Ver Demanda -->

    <!-- Pestaña Consultar Demanda -->
    <div class="tab-pane fade {% if demanda_consulta %}show active{% endif %}" id="consultar" role="tabpanel" aria-labelledby="consultar-tab">
      <div class="card mt-3">
        <div class="card-body">
          <form method="GET" action="{{ url_for('demanda.consultar_demanda') }}">
            <div class="row mb-3">
              <div class="col">
                <label>{{ form.fecha_inicio.label }}</label>
                <input type="month" name="fecha_inicio" class="form-control mb-3" value="{{ request.args.get('fecha_inicio', '') }}">
              </div>
              <div class="col">
                <label>{{ form.fecha_fin.label }}</label>
                <input type="month" name="fecha_fin" class="form-control mb-3" value="{{ request.args.get('fecha_fin', '') }}">
              </div>
              <div class="col">
                <label>{{ form.articulo_id.label }}</label>
                {{ form.articulo_id(class="form-control mb-3") }}
              </div>
            </div>
            <div class="col d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">Buscar Demanda</button>
            </div>
          </form>
        </div>
      </div>

      {% if demanda_consulta %}
      <div class="table-responsive mt-3">
        <table class="table table-striped table-sm table-bordered">
          <thead>
            <tr>
              <th scope="col" class="text-center align-middle">Codigo de Demanda</th>
              <th scope="col" class="text-center align-middle">Cantidad</th>
              <th scope="col" class="text-center align-middle">Código Artículo</th>
              <th scope="col" class="text-center align-middle">Nombre Artículo</th>
              <th scope="col" class="text-center align-middle">Fecha Demanda</th>
            </tr>
          </thead>
          <tbody>
            {% for consulta in demanda_consulta %}
            <tr>
              <td class="text-center align-middle">{{ consulta.id }}</td>
              <td class="text-center align-middle">{{ consulta.cantidad }}</td>
              <td class="text-center align-middle">{{ consulta.articulo.codigo_articulo }}</td>
              <td class="text-center align-middle">{{ consulta.articulo.nombre_articulo }}</td>
              <td class="text-center align-middle">{{ consulta.fecha_d }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% endif %}
    </div>
    <!-- Fin Pestaña Consultar Demanda -->
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBogGzjI4I4zW8G4PS7vvJzGOKjTIG8pf7LJATxtVf6CkzQK" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuLaS8h1FlkdzJ7T5fHTmZJg0uQ84ls0i+b1qaD6rrZzQ8Ck5W2hbUId8+VYkYr6" crossorigin="anonymous"></script>

<script>
  document.addEventListener('DOMContentLoaded', (event) => {
      var activeTab = localStorage.getItem('activeTab');
      if (activeTab) {
          var tab = new bootstrap.Tab(document.querySelector(`#${activeTab}-tab`));
          tab.show();
      }
  
      var tabLinks = document.querySelectorAll('.nav-tabs .nav-link');
      tabLinks.forEach(link => {
          link.addEventListener('shown.bs.tab', function (e) {
              localStorage.setItem('activeTab', e.target.id.replace('-tab', ''));
          });
      });
  });
  </script>
{% endblock %}