app/views/demandaPredecida.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app import db
from app.models import *
from app.forms import  ParametrosGeneralesPrediccionForm, PromedioMovilPonderadoForm

bp = Blueprint('demanda_predecida', __name__, url_prefix='/demanda_predecida')

@bp.route('/', methods=['GET', 'POST'])
def index():
    form = ParametrosGeneralesPrediccionForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]
    promedio_movil_ponderado_form=PromedioMovilPonderadoForm()
    promedio_movil_ponderado_form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]
    
    errores = ErrorDemandaPredecida.query.all()
    return render_template('demanda_predecida/index.html', form=form , errores=errores,promedio_movil_ponderado_form=promedio_movil_ponderado_form)

@bp.route('/parametros', methods=['GET', 'POST'])
def parametros():
    form = ParametrosGeneralesPrediccionForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]
    
    return render_template('demanda_predecida/index.html', form=form )


@bp.route('/promedio_movil', methods=['GET', 'POST'])
def promedio_movil():
    form = ParametrosGeneralesPrediccionForm()

    if form.validate_on_submit():
        articulo_id = form.articulo_id.data
        periodos = form.cantidad_periodos.data
        
        try:
            errorD=DemandaPredecida.error_predecir_promedio_movil(articulo_id,periodos)
            prediccion = DemandaPredecida.predecir_promedio_movil(articulo_id, periodos)
            flash(f'Demanda predecida usando Promedio Móvil: {prediccion}', 'success')
            nueva_demanda_predecida = DemandaPredecida(
                    cantidad_periodos=periodos,
                    articulo_id=articulo_id,
                    nombreMetodo= 'promedio movil',
                    error_DP=errorD
                ) 
            try:
                db.session.add(nueva_demanda_predecida)
                db.session.commit()
                flash('Demanda error predecida guardada con éxito!', 'success')
            except ValueError as e:
                flash(f'no se pudo crear la clase error 1: {str(e)}', 'danger') 
            return redirect(url_for('demandaPredecida.index'))          
        except ValueError as e:
            flash(f'no se pudo crear la clase error 2: {str(e)}', 'danger')
        return redirect(url_for('demanda_predecida.idex'))
    return render_template('demanda_predecida/index.html', form=form)

@bp.route('/promedio_movil_ponderado', methods=['GET', 'POST'])
def promedio_movil_ponderado():
    flash('promedio movil ponderado', 'danger')   
    form = PromedioMovilPonderadoForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]

    if form.validate_on_submit():
        articulo_id = form.articulo_id.data
        periodos = form.cantidad_periodos.data
        factores_ponderacion = [float(f.factor.data) for f in form.factores_ponderacion]
        
        try:
            
            error = DemandaPredecida.error_predecir_promedio_movil_ponderado(articulo_id, periodos, factores_ponderacion)
            flash(f'Error calculado con exito:', 'success')
            erroDemandaPredecida = ErrorDemandaPredecida(
                    articulo_ID=articulo_id,
                    error_DP=error,
                    nombreMetodo= 'promedio movil ponderado',
                    #metodo_calculo_error=ParametrosGeneralesPrediccion.query.first().modelo_calculo_error.nombre,
                    factores_de_ponderacion= str(factores_ponderacion)
                ) 
            try:
                db.session.add(erroDemandaPredecida)
                db.session.commit()
                flash('Error generado con éxito', 'success')
                return render_template('demanda_predecida/index.html', form=form)
            except Exception as e:
                db.session.rollback()
                flash(f'Error al generar el error con PMP: {str(e)}', 'danger')      
        
        except ValueError as e:
            flash(str(e), 'danger')

        return render_template('demanda_predecida/index.html', form=form)
    
    if form.errors:
        flash(f'Errores en el formulario: {form.errors}', 'danger')
        print("Errores del formulario:", form.errors) 
        
    return render_template('demanda_predecida/index.html', form=form)

@bp.route('/promedio_movil_suavizado', methods=['GET', 'POST'])
def promedio_movil_suavizado():
    form = ParametrosGeneralesPrediccionForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]
    
    if form.validate_on_submit():
        articulo_id = form.articulo_id.data
        alfa = form.alfa.data
        prediccion_raiz = form.prediccion_raiz.data
        periodos=form.cantidad_periodos.data

        try:
            errorD=DemandaPredecida.error_predecir_promedio_movil_suavizado(articulo_id,alfa,prediccion_raiz )
            prediccion = DemandaPredecida.predecir_promedio_movil_suavizado(articulo_id, alfa, prediccion_raiz)
            flash(f'Demanda predecida usando Promedio Móvil Suavizado: {prediccion}', 'success')
            nueva_demanda_predecida = DemandaPredecida(
                    cantidad_periodos=periodos,
                    alfa=alfa,
                    articulo_id=articulo_id,
                    nombreMetodo= 'promedio movil suavizado',
                    error_DP=errorD
                ) 
            try:
                db.session.add(nueva_demanda_predecida)
                db.session.commit()
                flash('Demanda error predecida guardada con éxito!', 'success')
            except ValueError as e:
                flash(str(e), 'danger')
            return redirect(url_for('demandaPredecida.get_error'))          

        except ValueError as e:
            flash(str(e), 'danger')
        return redirect(url_for('demanda_predecida.resultados'))
    return render_template('demanda_predecida/index.html', form=form)

@bp.route('/regresionLineal', methods=['GET', 'POST'])
def regresion_lineal():
    form = ParametrosGeneralesPrediccionForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]

    if form.validate_on_submit():
        try:
            articulo_id = form.articulo_id.data
            prediccion = DemandaPredecida.predecir_regresion_lineal(articulo_id)
            flash(f'Predicción: {prediccion}', 'success')
            errorD=DemandaPredecida.error_predecir_regresion_lineal(articulo_id )

            nueva_demanda_predecida = DemandaPredecida(
                    
                    articulo_id=articulo_id,
                    nombreMetodo= 'regresion lineal',
                    error_DP=errorD

                ) 
            try:
                db.session.add(nueva_demanda_predecida)
                db.session.commit()
                flash('Demanda error predecida guardada con éxito!', 'success')
            except ValueError as e:
                flash(str(e), 'danger')
            return redirect(url_for('demandaPredecida.get_error'))          
    
        except Exception as e:
            flash(str(e), 'danger')
    return render_template('demanda_predecida/index.html', form=form)

@bp.route('/ajusteEstacional', methods=['GET', 'POST'])
def ajuste_estacional():
    form = ParametrosGeneralesPrediccionForm()
    form.articulo_id.choices = [(m.id, m.nombre_articulo) for m in Articulo.query.all()]

    if form.validate_on_submit():
        try:
            
            articulo_id = form.articulo_id.data
            indices_estacionales = [1.0] * 12  # Aquí puedes definir los índices estacionales adecuados
            predicciones = DemandaPredecida.predecir_ajuste_estacional(articulo_id, indices_estacionales)
            flash(f'Predicciones: {predicciones}', 'success')
            
            nueva_demanda_predecida = DemandaPredecida(
                    
                    articulo_id=articulo_id,
                    nombreMetodo= 'ajuste estacional'
                ) 
            try:
                db.session.add(nueva_demanda_predecida)
                db.session.commit()
                flash('Demanda error predecida guardada con éxito!', 'success')
            except ValueError as e:
                flash(str(e), 'danger')
            return redirect(url_for('demandaPredecida.get_error'))          

        except Exception as e:
            flash(str(e), 'danger')
    return render_template('demanda_predecida/index.html', form=form)


@bp.route('/resultados', methods=['GET'])
def resultados():
    demandas_predecidas = DemandaPredecida.query.all()
    return render_template('demanda_predecida/index.html', demandas_predecidas=demandas_predecidas)

app/views/inventario.py
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, redirect, url_for, jsonify # type: ignore
from app import db
from app.models import *
from app.models import Articulo, OrdenCompra

bp = Blueprint('inventario', __name__, url_prefix='/inventario')

@bp.route('/', methods=['GET', 'POST'])
def articulos_a_reponer_bajo_stock():
    # Obtener todos los artículos
    articulos = Articulo.query.all()
    articulos_a_reponer = []

    # Filtrar artículos con modelo lote fijo que tienen stock <= calcular_punto_de_pedido
    articulos_bajo_stock_modelo_lote_fijo = [articulo for articulo in articulos if articulo.stock <= articulo.calcular_punto_de_pedido() and articulo.modelo_inventario.nombre == 'Lote fijo']

    # Filtrar artículos con modelo Intervalo fijo que hayan pasado el tiempo de pedido desde la fecha de la última orden de compra
    # Fecha actual
    fecha_actual = datetime.datetime.now().date()
    for articulo in articulos:
        if articulo.modelo_inventario.nombre == 'Intervalo fijo':
            ultima_orden = OrdenCompra.query.filter_by(articulo_id=articulo.id).order_by(OrdenCompra.fecha.desc()).first()
            if ultima_orden:
                dias_desde_ultima_orden = (fecha_actual - ultima_orden.fecha).days
                if articulo.tiempo_de_pedido <= dias_desde_ultima_orden:
                    articulos_a_reponer.append(articulo)
            else:
                articulos_a_reponer.append(articulo)

    
    articulos_bajo_stock_modelo_lote_fijo = [articulo for articulo in articulos if articulo.stock <= articulo.calcular_punto_de_pedido() and articulo.modelo_inventario.nombre == 'Lote fijo']

    # Filtrar artículos con modelo lote fijo sin órdenes de compra pendientes
    for articulo in articulos_bajo_stock_modelo_lote_fijo:
        orden_en_curso = OrdenCompra.query.filter_by(articulo_id=articulo.id, estado_id='En curso').first()
        if not orden_en_curso:
            articulos_a_reponer.append(articulo)


    # Filtrar artículos bajo el stock de seguridad
    articulos_bajo_stock_seguridad = [articulo for articulo in articulos if articulo.stock <= articulo.calcular_stock_de_seguridad()]

    return render_template('inventario/articulos_a_reponer_bajo_stock.html', articulos_a_reponer=articulos_a_reponer,
                                                                  articulos_bajo_stock_seguridad=articulos_bajo_stock_seguridad)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">

    {% block head %}{% endblock %}   <!-- esto lo hacemos para no estar poniendo toda la estructura de html en todas la paginas, es decir este bloque puede ser escripo por cualquier pagina que la extienda-->
</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Gestión de Inventario</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        
      </header>

      <div class="container-fluid">
        <div class="row">
          <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url_for('articulos.get_articulos') %}active{% endif %}" aria-current="page"href="http://127.0.0.1:5000/articulos/">
                    <span data-feather="home"></span>
                    Articulos
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url_for('ordenCompra.get_ordenes_compra') %}active{% endif %}" href="http://127.0.0.1:5000/ordenCompra/">
                    <span data-feather="file"></span>
                    Orden Compra
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url_for('ventas.get_ventas') %}active{% endif %}"href="http://127.0.0.1:5000/ventas/">
                    <span data-feather="shopping-cart"></span>
                    Ventas
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url_for('demanda.get_demanda') %}active{% endif %}"href="http://127.0.0.1:5000/demanda/">
                    <span data-feather="users"></span>
                    Demanda
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url_for('inventario.articulos_a_reponer_bajo_stock') %}active{% endif %}" href="http://127.0.0.1:5000/inventario/">
                    <span data-feather="bar-chart-2"></span>
                    Inventario
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url_for('proveedores.index') %}active{% endif %}" href="http://127.0.0.1:5000/proveedores/">
                    <span data-feather="layers"></span>
                    Proveedores
                  </a>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == url_for('demanda_predecida.index') %}active{% endif %}" href="http://127.0.0.1:5000/demanda_predecida/">
                      <span data-feather="users"></span>
                      Demanda Predecida
                    </a>
                </li>
              </ul>
            </div>
          </nav>
      
          <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <!--Esta parte es para recibir los mensajes flash-->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                <div class="mt-2">
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show fade-out" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                  {% endfor %}
                </div>
              {% endif %}
            {% endwith %}
            
            {% block body %}{% endblock %}
      
          </main>
        </div>
      </div>

    
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
    <script>
      feather.replace()

     // Para esconder las alertas a los 10 segundos
      setTimeout(function() {
        let alerts = document.querySelectorAll('.fade-out');
        alerts.forEach(function(alert) {
          alert.classList.remove('show');
        });
      }, 10000);
    </script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>
</html>